kind: ConfigMap 
apiVersion: v1 
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::618020673772:user/github-ci
      username: github-ci
      groups:
        - system:masters  